"""
Django settings for Legajo project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from urllib.parse import urlparse

import pymysql  # pyright: ignore[reportMissingModuleSource]
pymysql.version_info = (2, 2, 8, "final", 0)
pymysql.__version__ = "2.2.8"
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def _get_cloudinary_settings():
    cloudinary_url = os.environ.get('CLOUDINARY_URL', '').strip()
    cloud_name = os.environ.get('LEGAJO_CLOUDINARY_CLOUD_NAME', '').strip()
    api_key = os.environ.get('LEGAJO_CLOUDINARY_API_KEY', '').strip()
    api_secret = os.environ.get('LEGAJO_CLOUDINARY_API_SECRET', '').strip()

    if cloudinary_url:
        parsed = urlparse(cloudinary_url)
        if parsed.scheme == 'cloudinary':
            cloud_name = parsed.hostname or cloud_name
            api_key = parsed.username or api_key
            api_secret = parsed.password or api_secret

    return {
        'cloud_name': cloud_name,
        'api_key': api_key,
        'api_secret': api_secret,
        'folder': os.environ.get('LEGAJO_CLOUDINARY_FOLDER', 'legajo/libros').strip() or 'legajo/libros',
    }


_load_local_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!-baxdgkz2r2m31=#g-4_e%474o#x!a@3f&vo^hbz4bp%g)pmw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
]

# Usa el modelo de usuario personalizado definido en web/models.py
AUTH_USER_MODEL = 'web.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Legajo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'web' / 'usuarios' / 'templates',
            BASE_DIR / 'web' / 'administracion' / 'templates',
            BASE_DIR / 'web' / 'gestion_libros' / 'templates',
            BASE_DIR / 'web' / 'intercambios' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Legajo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'Legajo.mysql_backend',
        'NAME': 'LegajoDB',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'web' / 'usuarios' / 'static',
    BASE_DIR / 'web' / 'administracion' / 'static',
    BASE_DIR / 'web' / 'gestion_libros' / 'static',
    BASE_DIR / 'web' / 'intercambios' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LEGAJO_CLOUDINARY = _get_cloudinary_settings()


# Email (SMTP Gmail)
EMAIL_BACKEND = os.environ.get('LEGAJO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('LEGAJO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('LEGAJO_EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('LEGAJO_EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('LEGAJO_EMAIL_HOST_PASSWORD', '').strip()
EMAIL_USE_TLS = os.environ.get('LEGAJO_EMAIL_USE_TLS', 'true').strip().lower() == 'true'
EMAIL_USE_SSL = os.environ.get('LEGAJO_EMAIL_USE_SSL', 'false').strip().lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('LEGAJO_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@legajo.local')
