"""
Django settings for Legajo project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def _get_cloudinary_settings():
    cloudinary_url = os.environ.get('CLOUDINARY_URL', '').strip()
    cloud_name = os.environ.get('LEGAJO_CLOUDINARY_CLOUD_NAME', '').strip()
    api_key = os.environ.get('LEGAJO_CLOUDINARY_API_KEY', '').strip()
    api_secret = os.environ.get('LEGAJO_CLOUDINARY_API_SECRET', '').strip()

    if cloudinary_url:
        parsed = urlparse(cloudinary_url)
        if parsed.scheme == 'cloudinary':
            cloud_name = parsed.hostname or cloud_name
            api_key = parsed.username or api_key
            api_secret = parsed.password or api_secret

    return {
        'cloud_name': cloud_name,
        'api_key': api_key,
        'api_secret': api_secret,
        'folder': os.environ.get('LEGAJO_CLOUDINARY_FOLDER', 'legajo/libros').strip() or 'legajo/libros',
    }


_load_local_env_file()


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name, default=None):
    value = os.environ.get(name, '')
    items = [item.strip() for item in value.split(',') if item.strip()]
    return items or (default or [])


def _get_database_settings():
    database_url = os.environ.get('DATABASE_URL', '').strip()
    if not database_url:
        if os.environ.get('RAILWAY_ENVIRONMENT'):
            raise ImproperlyConfigured(
                'DATABASE_URL must be configured with the Railway PostgreSQL connection URL.'
            )

        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'legajodb'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'legajo'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }

    parsed = urlparse(database_url)
    if os.environ.get('RAILWAY_ENVIRONMENT') and parsed.hostname in {'localhost', '127.0.0.1'}:
        raise ImproperlyConfigured(
            'DATABASE_URL points to localhost. Use the Railway PostgreSQL connection URL instead.'
        )

    database = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }

    query = parse_qs(parsed.query)
    sslmode = query.get('sslmode', [''])[0]
    if sslmode:
        database['OPTIONS'] = {'sslmode': sslmode}

    return database


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-!-baxdgkz2r2m31=#g-4_e%474o#x!a@3f&vo^hbz4bp%g)pmw',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=not os.environ.get('RAILWAY_ENVIRONMENT'))

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])
if os.environ.get('RAILWAY_ENVIRONMENT'):
    ALLOWED_HOSTS.extend(['.up.railway.app', '.railway.app'])

CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
if os.environ.get('RAILWAY_ENVIRONMENT'):
    CSRF_TRUSTED_ORIGINS.extend(['https://*.up.railway.app', 'https://*.railway.app'])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '3600'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
]

# Usa el modelo de usuario personalizado definido en web/models.py
AUTH_USER_MODEL = 'web.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Legajo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'web' / 'usuarios' / 'templates',
            BASE_DIR / 'web' / 'administracion' / 'templates',
            BASE_DIR / 'web' / 'gestion_libros' / 'templates',
            BASE_DIR / 'web' / 'intercambios' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Legajo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': _get_database_settings()
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'web' / 'usuarios' / 'static',
    BASE_DIR / 'web' / 'administracion' / 'static',
    BASE_DIR / 'web' / 'gestion_libros' / 'static',
    BASE_DIR / 'web' / 'intercambios' / 'static',
]
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': os.environ.get(
            'DJANGO_STATICFILES_STORAGE',
            'whitenoise.storage.CompressedStaticFilesStorage',
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LEGAJO_CLOUDINARY = _get_cloudinary_settings()


# Email (SMTP Gmail)
EMAIL_BACKEND = os.environ.get('LEGAJO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('LEGAJO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('LEGAJO_EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('LEGAJO_EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('LEGAJO_EMAIL_HOST_PASSWORD', '').strip()
EMAIL_USE_TLS = os.environ.get('LEGAJO_EMAIL_USE_TLS', 'true').strip().lower() == 'true'
EMAIL_USE_SSL = os.environ.get('LEGAJO_EMAIL_USE_SSL', 'false').strip().lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('LEGAJO_EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.environ.get('LEGAJO_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@legajo.local')
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()
RESEND_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', DEFAULT_FROM_EMAIL).strip()
LEGAJO_EMAIL_CONFIGURED = bool(RESEND_API_KEY) or EMAIL_BACKEND != 'django.core.mail.backends.smtp.EmailBackend' or (
    bool(EMAIL_HOST_USER) and bool(EMAIL_HOST_PASSWORD)
)
