# Generated by Django 6.0.3 on 2026-03-25 02:46

import web.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', web.models.UsuarioManager()),
            ],
        ),
    ]
