# Generated by Codex on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='pin_validacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
