# Generated by Django 6.0.3 on 2026-06-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_intercambio_cancelado_por'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionLibro',
        ),
    ]
